// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0JQUsbtg4I8R_X0oV9Uhlxr9XiP1XppU',
    appId: '1:699211692758:web:dcb8dd9abddf279591a777',
    messagingSenderId: '699211692758',
    projectId: 'tori-88644',
    authDomain: 'tori-88644.firebaseapp.com',
    databaseURL: 'https://tori-88644-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tori-88644.appspot.com',
    measurementId: 'G-8B17XF21HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirAWR5YYh_7NeR1Nt3d6b8pcNXsBiR4o',
    appId: '1:699211692758:android:9e386656e1fa494391a777',
    messagingSenderId: '699211692758',
    projectId: 'tori-88644',
    databaseURL: 'https://tori-88644-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tori-88644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYmsVK1Woqp6m8JHsq8uNjuToVJEDnyWE',
    appId: '1:699211692758:ios:4ccda8621de8e9a691a777',
    messagingSenderId: '699211692758',
    projectId: 'tori-88644',
    databaseURL: 'https://tori-88644-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tori-88644.appspot.com',
    iosClientId: '699211692758-vpu8ucub95mjm9k0144k7feof8itt8t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYmsVK1Woqp6m8JHsq8uNjuToVJEDnyWE',
    appId: '1:699211692758:ios:4ccda8621de8e9a691a777',
    messagingSenderId: '699211692758',
    projectId: 'tori-88644',
    databaseURL: 'https://tori-88644-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tori-88644.appspot.com',
    iosClientId: '699211692758-vpu8ucub95mjm9k0144k7feof8itt8t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tori',
  );
}
